### ISSUE TITLE
Starting server fails

### ISSUE THREAD

**Issue by enricobuehler** [astzweig/docker-wildduck#10]
System: Ubuntu 18.04.3 (LTS)
Docker-Engine: 19.03.5
Docker-Compose: 1.21.2

When trying to start Wildduck with docker-compose up the following error appears. 

Config is the same as the example, and FQDN etc. are provided.

`mail_1        | [INFO] [-] [core] Loading plugins`
`mail_1        | [INFO] [-] [core] Loading plugin: spf`
`mail_1        | [INFO] [-] [core] Loading plugin: clamd`
`mail_1        | [INFO] [-] [clamd] Loading excludes file`
`mail_1        | [INFO] [-] [core] Loading plugin: rspamd`
`mail_1        | [INFO] [-] [core] Loading plugin: dkim_verify`
`mail_1        | [INFO] [-] [core] Loading plugin: wildduck`
`mail_1        | [CRIT] [-] [core] Compiling plugin: wildduck failed`
`mail_1        | [CRIT] [-] [core] internal/modules/cjs/loader.js:638`
`mail_1        | [CRIT] [-] [core]     throw err;`
`mail_1        | [CRIT] [-] [core]     ^`
`mail_1        | [CRIT] [-] [core] `
`mail_1        | [CRIT] [-] [core] Error: Cannot find module 'mongodb'`
`mail_1        | [CRIT] [-] [core]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)`
`mail_1        | [CRIT] [-] [core]     at Function.Module._load (internal/modules/cjs/loader.js:562:25)`
`mail_1        | [CRIT] [-] [core]     at Module.require (internal/modules/cjs/loader.js:692:17)`
`mail_1        | [CRIT] [-] [core]     at require (internal/modules/cjs/helpers.js:25:18)`
`mail_1        | [CRIT] [-] [core]     at Object.<anonymous> (/var/nodemailer/haraka/plugins/wildduck/index.js:10:18)`
`mail_1        | [CRIT] [-] [core]     at Module._compile (internal/modules/cjs/loader.js:778:30)`
`mail_1        | [CRIT] [-] [core]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)`
`mail_1        | [CRIT] [-] [core]     at Module.load (internal/modules/cjs/loader.js:653:32)`
`mail_1        | [CRIT] [-] [core]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)`
`mail_1        | [CRIT] [-] [core]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)`
`mail_1        | [NOTICE] [-] [core] Shutting down`

**Comment by rqelibari** [comment]
This seems to be related to #9. Closing this issue in favour of #9.
