### ISSUE TITLE
Any plans on integrating upstream?

### ISSUE THREAD

**Issue by rakshith-ravi** [astzweig/docker-wildduck#11]
Are there any plans of integrating this upstream? A PR can be made to the upstream wildduck repo and we can maintain a common versioning that integrates along with the main wildduck instance

**Comment by rqelibari** [comment]
@rakshith-ravi It is on our list, but its not on the top.
This has already been discussed at the [wildduck](/nodemailer/wildduck) repository, in issue nodemailer/wildduck#71, by the way. As Andris states [there](https://github.com/nodemailer/wildduck/issues/71#issuecomment-482471245):

> If you'd like me to set up some Github webhooks to trigger once anything new is pushed to start some kind of a build then I could do that. I could also accept a Dockerfile and docker-compose files (or whatever else is needed) directly into WildDuck repo - but I would not be interested in maintaining these.

So if you are willing to integrate this docker repository upstream and maintain it afterwards, you are very welcome to.
