### ISSUE TITLE
Additional plugins from haraka

### ISSUE THREAD

**Issue by unixfox** [astzweig/docker-wildduck#14]
Is it possible to add plugins from haraka to docker-wildduck easily? If so how would I do that?

**Comment by rqelibari** [comment]
It's actually quite easy:

1. Install or grab the repository of the haraka plugin in the `install_haraka` function of ['scripts/98-install-services.sh'](https://github.com/astzweig/docker-wildduck/blob/master/scripts/98-install-services.sh#L33) file.

2. Configure the plugin in the startup script ['scripts/_haraka.sh'](https://github.com/astzweig/docker-wildduck/blob/master/scripts/_haraka.sh).

If you need further help, just reopen the issue.
