### ISSUE TITLE
Off Topic: astzweig.de HTTP is down

### ISSUE THREAD

**Issue by almereyda** [astzweig/docker-wildduck#15]
Since the Twitter profile seems unmaintained, and I cannot find another reference to Astzweig UG on the web, I am leaving a note here about the fact, that connections to http://astzweig.de cannot be established. It appears the webserver is down. This has been found after following the link in the README to

> *This project is part of the [Astzweig](http://astzweig.de) social responsibility program.*

```
$ nmap astzweig.de
Starting Nmap 7.70 ( https://nmap.org ) at 2020-04-14 18:20 CEST
Nmap scan report for astzweig.de (188.138.100.66)
Host is up (0.037s latency).
rDNS record for 188.138.100.66: hydrogen.astzweig.de
Not shown: 993 closed ports
PORT    STATE    SERVICE
22/tcp  open     ssh
25/tcp  open     smtp
135/tcp filtered msrpc
139/tcp filtered netbios-ssn
445/tcp filtered microsoft-ds
465/tcp open     smtps
993/tcp open     imaps

Nmap done: 1 IP address (1 host up) scanned in 9.87 seconds
```

**Comment by rqelibari** [comment]
@almereyda Thank you for noticing! This is intentionally though. Nevertheless we will keep you updated as we are working hard on our website in our spare time.
