### ISSUE TITLE
Optional clamAV

### ISSUE THREAD

**Issue by gamelaster** [astzweig/docker-wildduck#17]

**Comment by rqelibari** [comment]
@gamelaster Can you please describe your issue?

**Comment by gamelaster** [comment]
@rqelibari I'm sorry! Well, in the original setup scripts, there is clamAV optional to be installed, so it would be nice to have environment variable to enable / disable clamAV.

Thanks

**Comment by rqelibari** [comment]
I think I can do that, but unfortunately not in the next two or three weeks. Do you want to do a PR on this?

**Comment by rqelibari** [comment]
@gamelaster I will close this issue for now. I'd be glad to see a PR for this feature.
