### ISSUE TITLE
How to disable IMAP service?

### ISSUE THREAD

**Issue by jet10000** [astzweig/docker-wildduck#21]
I just want to use http api

**Comment by rqelibari** [comment]
Hi @jet10000,

Note:
This is a question concerning `wildduck` itself, so you should open issues like this over at [nodemailer/wildduck](https://github.com/nodemailer/wildduck).

Regarding the question:
You have to edit the configuration file at `/etc/nodemailer/wildduck/imap.toml` inside the container (or if mounted as a volume then there) and set `enable` to `false`.
