### ISSUE TITLE
Errors on startup

### ISSUE THREAD

**Issue by Alwinius** [astzweig/docker-wildduck#4]
There seems to be a problem with the ENABLE_STARTTLS env during startup. I installed on clean Ubuntu 18.04 with Docker version 18.09.1. I did not set the variable, as it was by default. If I set it to false manually, it's the same. Only if I set it to true, the error will disappear. The second error potentially means that the directory is not being created during config initialisation.

`mail_1   | You have supplied an invalid value for  ENABLE_STARTTLS (false). Setting it to default value: false`

`mail_1   | /usr/local/bin/link_dkim_keys: cd: line 18: can't cd to /etc/nodemailer/dkim: No such file or directory
`

**Comment by drzaiusx11** [comment]
I get the same error too running both the docker hub version and the self-compiled docker-compose yamls

**Comment by drzaiusx11** [comment]
after removing any intermediary images from my local docker and rebuilding everything works!
