### ISSUE TITLE
SECURITY: API_TOKEN has no effect - exposes API to public

### ISSUE THREAD

**Issue by Alwinius** [astzweig/docker-wildduck#5]
The environment variable API_TOKEN in docker-compose.yml and docker-compose.hub.yml has no effect - it needs to be called API_TOKEN_SECRET as described in the readme.

**Comment by Alwinius** [comment]
#6 I thought instead of just complaining, I start fixing things myself.

**Comment by rqelibari** [comment]
> #6 I thought instead of just complaining, I start fixing things myself.

That's the way to go! BTW: No need to open an issue If you fixed the problem already (ain't no issue anymore).

**Comment by Alwinius** [comment]
I decided later, that I wanted to fix it myself.
