### ISSUE TITLE
How to update docker-wildduck from old version to latest?

### ISSUE THREAD

**Issue by jet10000** [astzweig/docker-wildduck#8]
How to backup data and settings?

Any suggestion?

**Comment by rqelibari** [comment]
Can you please post your configuration? E.g. the specific part of your `docker-compose.yml` or the `docker` command you run your container with.

**Comment by jet10000** [comment]
my docker-compose.yml just like https://github.com/astzweig/docker-wildduck/blob/master/docker-compose.yml with only change 

```
            - FQDN=mailserver1.example.com
            - MAIL_DOMAIN=example.com
           - API_URL=https://mailserver1.astzweig.de:5438
```

docker command just run `docker-compose up -d mail`

I want to use latest `astzweig/docker-wildduck`, but my mail server has data and settings. 

how to backup these and import to new?

**Comment by rqelibari** [comment]
If you use the default `docker-compose.yml` your mail data and configuration are already being persisted in the `docker` volumes `mongodbs` and `mailconfig`. To update the container you can follow the [instructions on this thread](https://stackoverflow.com/questions/49316462/how-to-update-existing-images-with-docker-compose)  and run the following commands in your `docker-compose.yml` directory:

```bash
$ docker-compose pull mail
$ docker-compose restart mail
$ docker image prune -f
```
